name: ✏️ matrix

on:
    workflow_call:
        outputs:
            os:
                value: ${{ jobs.compute.outputs.os }}
            coverage:
                value: ${{ jobs.compute.outputs.coverage }}
            php:
                value: ${{ jobs.compute.outputs.php }}
            exclude:
                value: ${{ jobs.compute.outputs.exclude }}

env:
    OS: '[ "ubuntu-latest" ]'
    COVERAGE: '[ "~9.0.0", "~9.1.0", "~9.2.0", "~10.0.0", "~10.1.0" ]'
    PHP: '[ "8.0", "8.1", "8.2", "8.3" ]'
    EXCLUDE: '[ { "coverage": "~10.0.0", "php": "8.0" }, { "coverage": "~10.1.0", "php": "8.0" } ]'

jobs:
    compute:
        name: Compute outputs

        runs-on: ubuntu-latest

        outputs:
            os: ${{ env.OS }}
            coverage: ${{ env.COVERAGE }}
            php: ${{ env.PHP }}
            exclude: ${{ env.EXCLUDE }}

        steps:
            -   name: Pseudo step
                if: false
                run: echo
